# -*- coding: utf-8 -*-
"""Energy Consumption Forecasting Capstone

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10zNxijIyuMhVmUVSabjeiS7o_Ap0KFZB
"""

## Uploading final SQL file

from google.colab import files

uploaded = files.upload()

## Loading the data

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Getting the uploaded file name automatically
file_name = list(uploaded.keys())[0]

# Load the CSV file
df = pd.read_csv(file_name)

# Show first 5 rows
df.head()

## Checking the shape and columns

print("Rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

## Checking data types

df.info()

## Converting date column

df["energy_date"] = pd.to_datetime(df["energy_date"])

df[["energy_date", "year", "month"]].head()

## Cleaning numeric columns

numeric_cols = [
    "com_revenue_thousand_dollars",
    "com_sales_mwh",
    "com_customers",
    "com_price_cents_per_kwh",
    "median_household_income",
    "poverty_rate",
    "employment_rate",
    "total_population",
    "total_housing_units",
    "price_poverty_interaction",
    "sales_mwh_per_customer",
    "sales_lag_1_month",
    "sales_lag_12_month"
]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

df.info()

## Checking missing values

df.isnull().sum()

## Removing rows that cannot be modeled

model_df = df.dropna(subset=[
    "com_sales_mwh",
    "com_price_cents_per_kwh",
    "com_customers",
    "median_household_income",
    "poverty_rate",
    "employment_rate",
    "total_population",
    "sales_lag_1_month",
    "sales_lag_12_month"
]).copy()

print("Original rows:", df.shape[0])
print("Rows after cleaning:", model_df.shape[0])

## Sorting the data by time

model_df = model_df.sort_values(["state_code", "energy_date"])

model_df.head()

## Creating time features

model_df["year_num"] = model_df["energy_date"].dt.year
model_df["month_num"] = model_df["energy_date"].dt.month
model_df["quarter"] = model_df["energy_date"].dt.quarter

model_df[["energy_date", "year_num", "month_num", "quarter"]].head()

## Energy usage over time chart

monthly_trend = model_df.groupby("energy_date")["com_sales_mwh"].sum()

plt.figure(figsize=(12, 5))
plt.plot(monthly_trend.index, monthly_trend.values)
plt.title("Total Commercial Electricity Sales Over Time")
plt.xlabel("Date")
plt.ylabel("Commercial Sales (MWh)")
plt.xticks(rotation=45)
plt.show()

## Seasonality chart

seasonality = model_df.groupby("month_num")["com_sales_mwh"].mean()

plt.figure(figsize=(8, 5))
plt.bar(seasonality.index, seasonality.values)
plt.title("Average Commercial Electricity Sales by Month")
plt.xlabel("Month")
plt.ylabel("Average Commercial Sales (MWh)")
plt.xticks(range(1, 13))
plt.show()

## Price vs energy use chart

plt.figure(figsize=(8, 5))
plt.scatter(model_df["com_price_cents_per_kwh"], model_df["com_sales_mwh"], alpha=0.5)
plt.title("Commercial Electricity Price vs Sales")
plt.xlabel("Commercial Price (cents per kWh)")
plt.ylabel("Commercial Sales (MWh)")
plt.show()

## Poverty and price interaction chart

plt.figure(figsize=(8, 5))
plt.scatter(model_df["price_poverty_interaction"], model_df["com_sales_mwh"], alpha=0.5)
plt.title("Price-Poverty Interaction vs Commercial Electricity Sales")
plt.xlabel("Price × Poverty Rate")
plt.ylabel("Commercial Sales (MWh)")
plt.show()

## Choosing target and features

target = "com_sales_mwh"

features = [
    "com_price_cents_per_kwh",
    "com_customers",
    "median_household_income",
    "poverty_rate",
    "employment_rate",
    "total_population",
    "price_poverty_interaction",
    "sales_mwh_per_customer",
    "sales_lag_1_month",
    "sales_lag_12_month",
    "year_num",
    "month_num",
    "quarter"
]

X = model_df[features]
y = model_df[target]

X.head()

## Create time-based train/test split

# Sort by date
model_df = model_df.sort_values("energy_date")

# Use the last 12 months as test data
cutoff_date = model_df["energy_date"].max() - pd.DateOffset(months=12)

train_df = model_df[model_df["energy_date"] <= cutoff_date].copy()
test_df = model_df[model_df["energy_date"] > cutoff_date].copy()

X_train = train_df[features]
y_train = train_df[target]

X_test = test_df[features]
y_test = test_df[target]

print("Training rows:", X_train.shape[0])
print("Testing rows:", X_test.shape[0])
print("Training period:", train_df["energy_date"].min(), "to", train_df["energy_date"].max())
print("Testing period:", test_df["energy_date"].min(), "to", test_df["energy_date"].max())

## Building Model 1 — Linear Regression

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

linear_model = LinearRegression()

linear_model.fit(X_train, y_train)

linear_pred = linear_model.predict(X_test)

## Build Model 2 — Random Forest

from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

## Create model evaluation function

def evaluate_model(y_true, y_pred, model_name):
    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2 = r2_score(y_true, y_pred)

    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

    return {
        "Model": model_name,
        "MAE": mae,
        "RMSE": rmse,
        "MAPE (%)": mape,
        "R2": r2
    }

results = []

results.append(evaluate_model(y_test, linear_pred, "Linear Regression"))
results.append(evaluate_model(y_test, rf_pred, "Random Forest"))

results_df = pd.DataFrame(results)

results_df

## Actual vs predicted chart

comparison_df = test_df[["energy_date", "state_name", "com_sales_mwh"]].copy()
comparison_df["predicted_sales_mwh"] = rf_pred

# Aggregate all states by month
actual_vs_pred = comparison_df.groupby("energy_date")[["com_sales_mwh", "predicted_sales_mwh"]].sum()

plt.figure(figsize=(12, 5))
plt.plot(actual_vs_pred.index, actual_vs_pred["com_sales_mwh"], label="Actual")
plt.plot(actual_vs_pred.index, actual_vs_pred["predicted_sales_mwh"], label="Predicted")
plt.title("Actual vs Predicted Commercial Electricity Sales")
plt.xlabel("Date")
plt.ylabel("Commercial Sales (MWh)")
plt.xticks(rotation=45)
plt.legend()
plt.show()

## Feature importance chart

feature_importance = pd.DataFrame({
    "feature": features,
    "importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values("importance", ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance["feature"], feature_importance["importance"])
plt.gca().invert_yaxis()
plt.title("Random Forest Feature Importance")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.show()

feature_importance

## State-level prediction error

comparison_df["absolute_error"] = abs(comparison_df["com_sales_mwh"] - comparison_df["predicted_sales_mwh"])
comparison_df["percentage_error"] = comparison_df["absolute_error"] / comparison_df["com_sales_mwh"] * 100

state_error = comparison_df.groupby("state_name").agg(
    avg_actual_sales=("com_sales_mwh", "mean"),
    avg_predicted_sales=("predicted_sales_mwh", "mean"),
    avg_absolute_error=("absolute_error", "mean"),
    avg_percentage_error=("percentage_error", "mean")
).reset_index()

state_error = state_error.sort_values("avg_percentage_error")

state_error.head(10)

## Saving final model results

comparison_df.to_csv("energy_prediction_results.csv", index=False)
results_df.to_csv("model_performance_summary.csv", index=False)
feature_importance.to_csv("feature_importance.csv", index=False)

files.download("energy_prediction_results.csv")
files.download("model_performance_summary.csv")
files.download("feature_importance.csv")